### ISSUE TITLE
Error Reading VCF

### ISSUE THREAD

**Issue by tatumdmortimer** [jamescasbon/PyVCF#164]
I'm getting an error reading VCFs that have been processed with snpEff. 

Here's my VCF header:

```
##fileformat=VCFv4.1
##INFO=<ID=AB,Number=1,Type=String,Description="Alt Base">
##SnpEffVersion="3.6c (build 2014-05-20), by Pablo Cingolani"
##SnpEffCmd="SnpEff  G_vaginalis_B1core -no-upstream -no-downstream - "
##INFO=<ID=EFF,Number=.,Type=String,Description="Predicted effects for this variant.Format: 'Effect ( Effect_Impact | Functional_Class | Codon_Change | Amino_Acid_Change| Amino_Acid_length | Gene_Name | Transcript_BioType | Gene_Coding | Transcript_ID | Exon_Rank  | Genotype_Number [ | ERRORS | WARNINGS ] )' ">
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  troy    284v    
```

Here's the error I get:

```
Traceback (most recent call last):
  File "/home/tmortimer/scripts/popgen-stats/siteFrequencySpectra.py", line 55, in <module>
    calc_freqs(vcfFile)
  File "/home/tmortimer/scripts/popgen-stats/siteFrequencySpectra.py", line 35, in calc_freqs
    for record in vcf_reader:
  File "/usr/local/lib/python2.7/dist-packages/PyVCF-0.6.7-py2.7-linux-x86_64.egg/vcf/parser.py", line 556, in next
    info = self._parse_info(row[7])
  File "/usr/local/lib/python2.7/dist-packages/PyVCF-0.6.7-py2.7-linux-x86_64.egg/vcf/parser.py", line 397, in _parse_info
    val = val[0]
TypeError: 'bool' object has no attribute '__getitem__'
```

This seems similar to Issue #78, but I haven't been able to figure out how to fix it. Thanks for any help!

**Comment by BGI-hys** [comment]
hello,I'm getting an error reading vcfs.
here is my vcf header:
![image](https://cloud.githubusercontent.com/assets/19663730/16514394/27bf5fc6-3f9e-11e6-9535-764cf60c59d2.png)
here is the error I get:
![image](https://cloud.githubusercontent.com/assets/19663730/16514407/47f0075a-3f9e-11e6-9c14-c2eaa08c6264.png)
