### ISSUE TITLE
UnicodeDecodeError using tabix indexed vcf

### ISSUE THREAD

**Issue by krlk89** [jamescasbon/PyVCF#217]
I compressed my vcf file with bgzip and indexed it with tabix. Trying to iterate over a specific chromosome gives me the following error:

```
Traceback (most recent call last):
  File "vcf_test.py", line 39, in <module>
    mask_seq()
  File "vcf_test.py", line 11, in mask_seq
    vcf = vcf.Reader(open(argv[1]))
  File "/home/krlk89/.local/lib/python3.4/site-packages/PyVCF-0.6.7-py3.4.egg/vcf/parser.py", line 288, in __init__
    self._parse_metainfo()
  File "/home/krlk89/.local/lib/python3.4/site-packages/PyVCF-0.6.7-py3.4.egg/vcf/parser.py", line 304, in _parse_metainfo
    line = next(self.reader)
  File "/home/krlk89/.local/lib/python3.4/site-packages/PyVCF-0.6.7-py3.4.egg/vcf/parser.py", line 268, in <genexpr>
    self.reader = (line.strip() for line in self._reader if line.strip())
  File "/home/krlk89/.local/lib/python3.4/codecs.py", line 638, in __next__
    line = self.readline()
  File "/home/krlk89/.local/lib/python3.4/codecs.py", line 551, in readline
    data = self.read(readsize, firstline=True)
  File "/home/krlk89/.local/lib/python3.4/codecs.py", line 491, in read
    newdata = self.stream.read(size)
  File "/home/krlk89/.local/lib/python3.4/gzip.py", line 365, in read
    if not self._read(readsize):
  File "/home/krlk89/.local/lib/python3.4/gzip.py", line 433, in _read
    if not self._read_gzip_header():
  File "/home/krlk89/.local/lib/python3.4/gzip.py", line 292, in _read_gzip_header
    magic = self.fileobj.read(2)
  File "/home/krlk89/.local/lib/python3.4/gzip.py", line 90, in read
    self.file.read(size-self._length+read)
  File "/home/krlk89/.local/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```
My code sample looks like this:
```
for record in vcf.fetch("1"):
    print(record)
```

**Comment by martijnvermaat** [comment]
Thanks for the report @krlk89 

Could you try with the Git master branch?

    pip install -e git+https://github.com/jamescasbon/PyVCF.git#egg=PyVCF

**Comment by krlk89** [comment]
I found issue #201 which seemed very similiar to mine and tried the development version, but sadly I'm getting the same error.

```
Traceback (most recent call last):
  File "vcf_test.py", line 39, in <module>
    mask_seq()
  File "vcf_test.py", line 11, in mask_seq
    vcf = vcf.Reader(open(argv[1]))
  File "/home/krlk89/.local/lib/python3.4/site-packages/PyVCF-0.6.8.dev0-py3.4.egg/vcf/parser.py", line 300, in __init__
    self._parse_metainfo()
  File "/home/krlk89/.local/lib/python3.4/site-packages/PyVCF-0.6.8.dev0-py3.4.egg/vcf/parser.py", line 317, in _parse_metainfo
    line = next(self.reader)
  File "/home/krlk89/.local/lib/python3.4/site-packages/PyVCF-0.6.8.dev0-py3.4.egg/vcf/parser.py", line 280, in <genexpr>
    self.reader = (line.strip() for line in self._reader if line.strip())
  File "/home/krlk89/.local/lib/python3.4/codecs.py", line 638, in __next__
    line = self.readline()
  File "/home/krlk89/.local/lib/python3.4/codecs.py", line 551, in readline
    data = self.read(readsize, firstline=True)
  File "/home/krlk89/.local/lib/python3.4/codecs.py", line 491, in read
    newdata = self.stream.read(size)
  File "/home/krlk89/.local/lib/python3.4/gzip.py", line 365, in read
    if not self._read(readsize):
  File "/home/krlk89/.local/lib/python3.4/gzip.py", line 433, in _read
    if not self._read_gzip_header():
  File "/home/krlk89/.local/lib/python3.4/gzip.py", line 292, in _read_gzip_header
    magic = self.fileobj.read(2)
  File "/home/krlk89/.local/lib/python3.4/gzip.py", line 90, in read
    self.file.read(size-self._length+read)
  File "/home/krlk89/.local/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by martijnvermaat** [comment]
Could you put up (part of) a VCF file somewhere to test with, for example in a Gist?

**Comment by krlk89** [comment]
Sure thing. https://gist.github.com/krlk89/035c2702eb4c0fb89195

**Comment by martijnvermaat** [comment]
Sorry, can't reproduce this on Python 2.7 or Python 3.4, both with current pysam 0.8.4. What's you pysam version? Check with

    pip freeze | grep pysam

Perhaps it's better to share the bgzipped and tabixed instead of the plain text VCF. I don't think that's possible with the Gist web interface, though it is by cloning the Gist repo, adding a file manually and pushing back.

**Comment by krlk89** [comment]
Hmm, I don't have pysam installed. Did not see it listed anywhere as a dependency, upon trying to install it now with pip i get an error about missing Python.h file.

**Comment by martijnvermaat** [comment]
The `fetch` method on a reader requires pysam.

Missing `Python.h` looks like you need Python development headers. On
Debian/Ubuntu based systems this is called `python-dev` (or the 3.4
equivalent), not sure about others.

2015-11-27 11:51 GMT+01:00 Kaarel <notifications@github.com>:

**Comment by krlk89** [comment]
Yeah, I have python-dev installed. :\

**Comment by podpearson** [comment]
FWIW I got this same error when using vcf.Reader(open('filename.vcf.gz')), but it worked fine using vcf.Reader(filename='filename.vcf.gz'). This was using python 3.5.2 (miniconda), pysam 0.8.4 and vcf 0.6.8.

**Comment by keoughkath** [comment]
@podpearson thanks for your tip, that solved my issue.

**Comment by ryantkoehler** [comment]
Using vcf.Reader(filename='filename.vcf.gz') fixed things for me. Thanks.
