### ISSUE TITLE
invalid literal for float() when parsing VCF records

### ISSUE THREAD

**Issue by darencard** [jamescasbon/PyVCF#242]
I'm having an issue that appears to occur when parsing VCF records that I fetched from a tabix-indexed VCF file. Here is the traceback:

```
Traceback (most recent call last):
  File "vcfconsensus", line 267, in <module>
    main(sys.argv)
  File "vcfconsensus", line 216, in main
    for record in vcf_in.fetch(seqNameTuple[0], seqNameTuple[1], seqNameTuple[2]):
  File "//anaconda/lib/python2.7/site-packages/vcf/parser.py", line 586, in next
    samples = self._parse_samples(row[9:], fmt, record)
  File "//anaconda/lib/python2.7/site-packages/vcf/parser.py", line 451, in _parse_samples
    self.samples, samples, samp_fmt, samp_fmt._types, samp_fmt._nums, site)
  File "vcf/cparse.pyx", line 57, in vcf.cparse.parse_samples (vcf/cparse.c:1552)
ValueError: invalid literal for float(): 0,3,32
```

I've read in the VCF using:
```
vcf_in = vcf.Reader(filename=args.vcf)
```
where `args.vcf` is reading the VCF file name from python command-line arguments. From here I'm following the documentation and am fetching from the Reader:
```
for record in vcf_in.fetch(seqNameTuple[0], seqNameTuple[1], seqNameTuple[2]):
```
The seqNameTuple is simply a tuple of `(chrom, start, end)` that I've parsed from a FASTA header.

The VCF is v.4.2 and records look like this (with more samples than just 2... I've abbreviated).
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Pymo063	Pymo067
NW_006532014.1	257889	.	G	C	34.75	PASS	AN=174;AC=2	GT:AD:DP:FT:GQ:PL	./.:.:.:PASS:.:.	0/0:132,0:132:PASS:99:0,394,4900
NW_006532014.1	275657	.	C	T	446.12	PASS	AN=176;AC=2	GT:AD:DP:FT:GQ:HP:PL	./.:.:.:PASS:.:.:.	0/0:169,0:169:PASS:99:.:0,499,6088
NW_006532014.1	332170	.	T	G	71819.1	PASS	AN=134;AC=133	GT:AD:DP:FT:GQ:HP:PL	./.:.:.:PASS:.:.:.	1/1:0,23:23:PASS:69:.:868,69,0
NW_006532014.1	376980	.	T	C	2066.56	PASS	AN=164;AC=4	GT:AD:DP:FT:GQ:HP:PL	./.:.:.:PASS:.:.:.	0/0:201,2:203:PASS:99:.:0,514,7833
NW_006532014.1	376981	.	C	T	218.08	PASS	AN=164;AC=2	GT:AD:DP:FT:GQ:HP:PL	./.:.:.:PASS:.:.:.	0/0:201,0:201:PASS:99:.:0,596,8071
NW_006532014.1	548411	.	C	T	388.5	PASS	AN=178;AC=1	GT:AD:DP:FT:GQ:HP:PL	./.:.:.:PASS:.:.:.	0/0:137,0:137:PASS:99:.:0,412,5489
NW_006532014.1	727775	.	A	C	603.39	PASS	AN=110;AC=2	GT:AD:DP:FT:GQ:PL	./.:.:.:PASS:.:.	0/0:9,0:9:PASS:27:0,27,327
NW_006532014.1	742459	.	G	A	1747.37	PASS	AN=182;AC=1	GT:AD:DP:FT:GQ:HP:PL	./.:.:.:PASS:.:.:.	0/0:243,0:243:PASS:99:.:0,719,9317
NW_006532014.1	1052825	.	G	A	32.53	PASS	AN=134;AC=1	GT:AD:DP:FT:GQ:HP:PL	./.:.:.:PASS:.:.:.	0/0:42,0:42:PASS:99:.:0,126,1660
NW_006532014.1	1172356	.	T	C	171261	PASS	AN=182;AC=179	GT:AD:DP:FT:GQ:HP:PL	./.:.:.:PASS:.:.:.	1/1:3,127:130:PASS:99:.:4420,269,0
NW_006532014.1	1172371	.	C	T	190104	PASS	AN=182;AC=182	GT:AD:DP:FT:GQ:PL	./.:.:.:PASS:.:.	1/1:1,155:156:PASS:99:5665,436,0
```

The problematic string from the error above is found in the 1st record of this VCF (confirmed via Grep). Any guidance on getting around this would be greatly appreciated, as I don't have the knowledge of Python to diagnose myself.

Thanks!
Daren

**Comment by darencard** [comment]
It looks like I was a bit premature in posting an issue, as spending some more time playing around led me to deduce the issue. Turns out the VCF I'm working with his some white-space and eliminating that solved the problem.
