### ISSUE TITLE
Reading multiple VCFs in a loop gives IOError

### ISSUE THREAD

**Issue by nuin** [jamescasbon/PyVCF#252]
Hi

I have a simple loop that iterates over a list of VCFs in a directory for comparison of variant calls and whenever I open the VCF inside the `Reader` call 

``` python
for i in range(1, 101):
    prob = '0' + str(prob_int)
    downsample_vcf = vcf.Reader(open(result_path + '/' + sample_id + '/' + prob + '/' + sample_id + '_' + str(i) + '_' + prob + '.vcf', 'r'))
...
```

it fails with this error

``` python
Traceback (most recent call last):
  File "extract_sensitivity.py", line 104, in <module>
    compare_variants(downsample_vcf, original_vcf)
  File "extract_sensitivity.py", line 56, in compare_variants
    for dvariant in vcf_file:
  File "parser.py", line 526, in next
    line = self.reader.next()
  File "parser.py", line 268, in <genexpr>
    self.reader = (line.strip() for line in self._reader if line.strip())
IOError: [Errno 9] Bad file descriptor
close failed in file object destructor:
IOError: [Errno 9] Bad file descriptor
```

If I open the VCF outside the `Reader` call, and just pass the stream to it, closing the stream after no error is output.

**Comment by jamescasbon** [comment]
Which python is this?

Why not use a with statement?

**Comment by nuin** [comment]
```
Python 2.7.12 (default, Jun 29 2016, 14:05:02)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin```

The easiest approach here was to use a loop, as this `open` operation is done on multiple files at the same time. Not a roadblock error, just reporting it.

**Comment by martijnvermaat** [comment]
Can you share a *complete* (but minimal) example that is failing? I don't know how to reproduce this.
