### ISSUE TITLE
How to read the vcf file when the items in the FORMAT columns are not always present?

### ISSUE THREAD

**Issue by everestial** [jamescasbon/PyVCF#256]
I have problem reading a vcf file. I thinks its because the items in the FORMAT field are not same in all the lines.
Something like this:

    FORMAT     2ms01e
    GT:AD:DP:PL:PG:PB:PI:PW:PC	./.:0,0:0:0,0,0:./.:.:.:./.:.
    GT:AD:DP:GQ:PGT:PID:PL:PG:PB:PI:PW:PC	0/0:620,0:620:99:.:.:0,120,1800:0/0:.:.:0/0:.

I am getting error message as:

`Traceback (most recent call last):
  File "/home/everestial007/PycharmProjects/stitcher/update_phase.py", line 41, in <module>
    PGT_phase = record.genotype('2ms01e')['PGT']
  File "/home/everestial007/anaconda3/lib/python3.5/site-packages/vcf/model.py", line 104, in __getitem__
    return getattr(self.data, key)
AttributeError: 'CallData' object has no attribute 'PGT'`

I didn't generate this vcf file and author should have been aware of updating the FORMAT columns with emtpy/null/period when no value is available for the FORMAT item.

Is there a way to read when the data in the FORMAT is in this way. Probably this problem can be solved in updated `pyVCF` package.

Thanks,

**Comment by lss1227** [comment]
I also meet this problem. Has this been solved?
