### ISSUE TITLE
ValueError: invalid literal for float()

### ISSUE THREAD

**Issue by stanedav** [jamescasbon/PyVCF#269]
Hello, 

I am trying to use your library to load and read VCF file, my code is:
```

import vcf

vcf_reader = vcf.Reader(open('6788.vcf', 'r'))

record = next(vcf_reader)
```
I tried Py2.7 and Py3.5 and got these errors:
Python 2.7:
```
Traceback (most recent call last):

  File "/Users/davidstanek/Dropbox/Skola/2LF UK/Python/vcf_filter27/filter_vcf_27.py", line 6, in <module>
    record = next(vcf_reader)
  File "/Library/Python/2.7/site-packages/vcf/parser.py", line 586, in next
    samples = self._parse_samples(row[9:], fmt, record)
  File "/Library/Python/2.7/site-packages/vcf/parser.py", line 483, in _parse_samples
    sampdat[i] = float(vals)
ValueError: invalid literal for float(): 0,255,255
```

Python 3.5:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/vcf/parser.py", line 481, in _parse_samples
    sampdat[i] = int(vals)
ValueError: invalid literal for int() with base 10: '0,255,255'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidstanek/Dropbox/Skola/2LF UK/Python/vcf_filtering/filter_vcf.py", line 6, in <module>
    record = next(vcf_reader)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/vcf/parser.py", line 586, in __next__
    samples = self._parse_samples(row[9:], fmt, record)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/vcf/parser.py", line 483, in _parse_samples
    sampdat[i] = float(vals)
ValueError: could not convert string to float: '0,255,255'
```

Can you please help with this error? Thank you

VCF is here: https://www.dropbox.com/s/rnkzp9635h0tmc5/6788.vcf?dl=0 (its 50 MB)
Few lines of VCF:
```
##fileformat=VCFv4.1									
##GeneratedBy=SureCall2.0 Snppet									
##INFO=<ID=DP,Number=1,Type=Integer,Description="Raw read depth">									
##INFO=<ID=DP4,Number=4,Type=Integer,Description="# high-quality ref-forward bases, ref-reverse, alt-forward and alt-reverse bases">									
##INFO=<ID=MQ,Number=1,Type=Float,Description="Root-mean-square mapping quality of covering reads">									
##INFO=<ID=AF1,Number=1,Type=Float,Description="estimate of the first ALT allele frequency">									
##INFO=<ID=AN,Number=1,Type=Float,Description="Total number of alleles in called genotypes">									
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">									
##FORMAT=<ID=PL,Number=1,Type=Integer,Description="List of Phred-scaled genotype likelihoods">									
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">									
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	6788
chr1	65529	.	C	T	255.0	PASS	ALTCOUNT=14;DP=51.0;DP4=27,11,9,5;AF1=0.27450982;MQ=41;IsKnownVariant=0;EFF=UPSTREAM(MODIFIER||||OR4F5|mRNA|CODING|NM_001005484|);SEL_PRIMARY_EFF=0;pValue=1.0E-255;Zygosity=HET;Category=Category//@IV-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/0:0,255,255:10
chr1	65591	.	C	T	255.0	PASS	ALTCOUNT=13;DP=59.0;DP4=21,26,6,7;AF1=0.22033899;MQ=41;IsKnownVariant=0;dbnsfpUniprot_acc;dbnsfpInterpro_domain;dbnsfpEnsembl_transcriptid;dbnsfpSIFT_score;dbnsfpGERP++_NR;dbnsfpGERP++_RS;dbnsfp29way_logOdds;dbnsfp1000Gp1_AF;dbnsfp1000Gp1_AFR_AF;dbnsfp1000Gp1_EUR_AF;dbnsfp1000Gp1_AMR_AF;dbnsfp1000Gp1_ASN_AF;dbnsfpESP5400_AA_AF;EFF=UPSTREAM(MODIFIER||||OR4F5|mRNA|CODING|NM_001005484|);SEL_PRIMARY_EFF=0;pValue=1.0E-255;Zygosity=HOM;Category=Category//@IV-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/0:0,255,255:10
chr1	65797	.	T	C	255.0	PASS	ALTCOUNT=10;DP=36.0;DP4=25,2,9,1;AF1=0.2777778;MQ=41;IsKnownVariant=0;dbnsfpUniprot_acc;dbnsfpInterpro_domain;dbnsfpEnsembl_transcriptid;dbnsfpSIFT_score;dbnsfpGERP++_NR;dbnsfpGERP++_RS;dbnsfp29way_logOdds;dbnsfp1000Gp1_AF;dbnsfp1000Gp1_AFR_AF;dbnsfp1000Gp1_EUR_AF;dbnsfp1000Gp1_AMR_AF;dbnsfp1000Gp1_ASN_AF;dbnsfpESP5400_AA_AF;EFF=UPSTREAM(MODIFIER||||OR4F5|mRNA|CODING|NM_001005484|);SEL_PRIMARY_EFF=0;pValue=1.0E-255;Zygosity=HET;Category=Category//@IV-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/0:0,255,255:10
chr1	65872	.	T	G	255.0	PASS	ALTCOUNT=31;DP=113.0;DP4=49,34,17,14;AF1=0.27433628;MQ=41;IsKnownVariant=0;dbnsfpUniprot_acc;dbnsfpInterpro_domain;dbnsfpEnsembl_transcriptid;dbnsfpSIFT_score;dbnsfpGERP++_NR;dbnsfpGERP++_RS;dbnsfp29way_logOdds;dbnsfp1000Gp1_AF;dbnsfp1000Gp1_AFR_AF;dbnsfp1000Gp1_EUR_AF;dbnsfp1000Gp1_AMR_AF;dbnsfp1000Gp1_ASN_AF;dbnsfpESP5400_AA_AF;EFF=UPSTREAM(MODIFIER||||OR4F5|mRNA|CODING|NM_001005484|);SEL_PRIMARY_EFF=0;pValue=1.0E-255;Zygosity=HET;Category=Category//@IV-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/0:0,255,255:10
chr1	69511	.	A	G	123.0	PASS	ALTCOUNT=84;DP=84.0;DP4=1,0,59,25;AF1=1.0;MQ=41;IsKnownVariant=0;dbnsfpUniprot_acc=Q8NH21;dbnsfpInterpro_domain=GPCR,_rhodopsin-like_superfamily_(1),;dbnsfpEnsembl_transcriptid=ENST00000534990,ENST00000335137;dbnsfpSIFT_score=0.950000;dbnsfpGERP++_NR=2.31;dbnsfpGERP++_RS=1.15;dbnsfp29way_logOdds=4.1978;dbnsfp1000Gp1_AF=0.652014652014652;dbnsfp1000Gp1_AFR_AF=0.32926829268292684;dbnsfp1000Gp1_EUR_AF=0.6952506596306068;dbnsfp1000Gp1_AMR_AF=0.649171270718232;dbnsfp1000Gp1_ASN_AF=0.8741258741258742;dbnsfpESP5400_AA_AF=0.568242;EFF=NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|Aca/Gca|T141A|OR4F5|mRNA|CODING|NM_001005484|NM_001005484.ex.1);SEL_PRIMARY_EFF=0;Mutation_Description(COSMIC)=Substitution_Missense;Mutation_cds_syntax=c.421A>G;Mutation_AA_syntax=p.T141A;Tumour_Site_(cosmic)=thyroid;Frequency_(cosmic)=100.00;HGVS_Syntax(COSMIC)=c.421A>Gp.T141A;Gene_Description=70008;pValue=1.0E-123;Zygosity=HOM;Category=Category//@II-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/1:0,0,255:255
chr1	752894	.	T	C	255.0	PASS	ALTCOUNT=36;DP=66.0;DP4=26,5,28,8;AF1=0.54545456;MQ=41;IsKnownVariant=0;EFF=SYNONYMOUS_CODING(LOW|SILENT|gcT/gcC|A48|FAM87B|Non-coding_transcript|NON_CODING|NR_103536|NR_103536.ex.1);SEL_PRIMARY_EFF=0;Gene_Description=755214;pValue=1.0E-255;Zygosity=HET;Category=Category//@III-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/0:0,255,255:10
chr1	762273	.	G	A	123.0	PASS	ALTCOUNT=69;DP=69.0;DP4=1,0,21,48;AF1=1.0;MQ=41;IsKnownVariant=0;EFF=SYNONYMOUS_CODING(LOW|SILENT|tcC/tcT|S210|LINC00115|Non-coding_transcript|NON_CODING|NR_024321|NR_024321.ex.1),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047519|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047521|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047523|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047524|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047525|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047526|);SEL_PRIMARY_EFF=0;Gene_Description=762902;pValue=1.0E-123;Zygosity=HOM;Category=Category//@III-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/1:0,0,255:255
chr1	762589	.	G	C	255.0	PASS	ALTCOUNT=10;DP=13.0;DP4=1,3,0,10;AF1=0.7692308;MQ=41;IsKnownVariant=0;EFF=NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|cCt/cGt|P105R|LINC00115|Non-coding_transcript|NON_CODING|NR_024321|NR_024321.ex.1),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047519|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047521|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047523|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047524|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047525|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047526|);SEL_PRIMARY_EFF=0;Gene_Description=762902;pValue=1.0E-255;Zygosity=HOM;Category=Category//@II-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/1:0,0,0:10
chr1	762592	.	C	G	255.0	PASS	ALTCOUNT=11;DP=13.0;DP4=1,2,1,10;AF1=0.84615386;MQ=41;IsKnownVariant=0;EFF=NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|cGg/cCg|R104P|LINC00115|Non-coding_transcript|NON_CODING|NR_024321|NR_024321.ex.1),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047519|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047521|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047523|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047524|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047525|),UPSTREAM(MODIFIER||||LINC01128|Non-coding_transcript|NON_CODING|NR_047526|);SEL_PRIMARY_EFF=0;Gene_Description=762902;pValue=1.0E-255;Zygosity=HOM;Category=Category//@II-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/0:0,255,255:10
chr1	792263	.	A	G	255.0	PASS	ALTCOUNT=31;DP=35.0;DP4=4,1,27,4;AF1=0.8857143;MQ=41;IsKnownVariant=0;EFF=NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|Act/Gct|T1322A|LINC01128|Non-coding_transcript|NON_CODING|NR_047523|NR_047523.ex.4),NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|Act/Gct|T1354A|LINC01128|Non-coding_transcript|NON_CODING|NR_047521|NR_047521.ex.5),NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|Act/Gct|T1405A|LINC01128|Non-coding_transcript|NON_CODING|NR_047519|NR_047519.ex.6),SYNONYMOUS_CODING(LOW|SILENT|gcA/gcG|A1292|LINC01128|Non-coding_transcript|NON_CODING|NR_047524|NR_047524.ex.4),SYNONYMOUS_CODING(LOW|SILENT|gcA/gcG|A1309|LINC01128|Non-coding_transcript|NON_CODING|NR_047525|NR_047525.ex.5);SEL_PRIMARY_EFF=0;Gene_Description=794826;pValue=1.0E-255;Zygosity=HOM;Category=Category//@II-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/0:0,255,255:10
chr1	792480	.	C	T	123.0	PASS	ALTCOUNT=91;DP=91.0;DP4=1,0,32,59;AF1=1.0;MQ=41;IsKnownVariant=0;EFF=NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|Cat/Tat|H1365Y|LINC01128|Non-coding_transcript|NON_CODING|NR_047524|NR_047524.ex.4),NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|Cat/Tat|H1382Y|LINC01128|Non-coding_transcript|NON_CODING|NR_047525|NR_047525.ex.5),NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|aCa/aTa|T1394I|LINC01128|Non-coding_transcript|NON_CODING|NR_047523|NR_047523.ex.4),NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|aCa/aTa|T1426I|LINC01128|Non-coding_transcript|NON_CODING|NR_047521|NR_047521.ex.5),NON_SYNONYMOUS_CODING(MODERATE|MISSENSE|aCa/aTa|T1477I|LINC01128|Non-coding_transcript|NON_CODING|NR_047519|NR_047519.ex.6);SEL_PRIMARY_EFF=0;Gene_Description=794826;pValue=1.0E-123;Zygosity=HOM;Category=Category//@II-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/1:0,0,255:255
chr1	866319	.	G	A	123.0	PASS	ALTCOUNT=17;DP=17.0;DP4=1,0,14,3;AF1=1.0;MQ=41;IsKnownVariant=0;dbnsfpUniprot_acc;dbnsfpInterpro_domain;dbnsfpEnsembl_transcriptid;dbnsfpSIFT_score;dbnsfpGERP++_NR;dbnsfpGERP++_RS;dbnsfp29way_logOdds;dbnsfp1000Gp1_AF;dbnsfp1000Gp1_AFR_AF;dbnsfp1000Gp1_EUR_AF;dbnsfp1000Gp1_AMR_AF;dbnsfp1000Gp1_ASN_AF;dbnsfpESP5400_AA_AF;EFF=INTRON(MODIFIER||||SAMD11|mRNA|CODING|NM_152486|);SEL_PRIMARY_EFF=0;OMIM_ID=OMIM:616765;Gene_Description=879961;pValue=1.0E-123;Zygosity=HOM;Category=Category//@III-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/1:0,0,255:255
chr1	880238	.	A	G	123.0	PASS	ALTCOUNT=70;DP=70.0;DP4=1,0,37,33;AF1=1.0;MQ=41;IsKnownVariant=0;dbnsfpUniprot_acc;dbnsfpInterpro_domain;dbnsfpEnsembl_transcriptid;dbnsfpSIFT_score;dbnsfpGERP++_NR;dbnsfpGERP++_RS;dbnsfp29way_logOdds;dbnsfp1000Gp1_AF;dbnsfp1000Gp1_AFR_AF;dbnsfp1000Gp1_EUR_AF;dbnsfp1000Gp1_AMR_AF;dbnsfp1000Gp1_ASN_AF;dbnsfpESP5400_AA_AF;EFF=DOWNSTREAM(MODIFIER||||SAMD11|mRNA|CODING|NM_152486|),INTRON(MODIFIER||||NOC2L|mRNA|CODING|NM_015658|);SEL_PRIMARY_EFF=1;OMIM_ID=OMIM:610770;Gene_Description=894679;pValue=1.0E-123;Zygosity=HOM;Category=Category//@III-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/1:0,0,255:255
chr1	881627	.	G	A	255.0	PASS	ALTCOUNT=19;DP=43.0;DP4=18,7,9,10;AF1=0.44186047;MQ=41;IsKnownVariant=0;dbnsfpUniprot_acc;dbnsfpInterpro_domain;dbnsfpEnsembl_transcriptid;dbnsfpSIFT_score;dbnsfpGERP++_NR;dbnsfpGERP++_RS;dbnsfp29way_logOdds;dbnsfp1000Gp1_AF;dbnsfp1000Gp1_AFR_AF;dbnsfp1000Gp1_EUR_AF;dbnsfp1000Gp1_AMR_AF;dbnsfp1000Gp1_ASN_AF;dbnsfpESP5400_AA_AF;EFF=DOWNSTREAM(MODIFIER||||SAMD11|mRNA|CODING|NM_152486|),SYNONYMOUS_CODING(LOW|SILENT|Ctg/Ttg|L615|NOC2L|mRNA|CODING|NM_015658|NM_015658.ex.16);SEL_PRIMARY_EFF=1;Mutation_Description(COSMIC)=Substitution_coding//\@silent;Mutation_cds_syntax=c.1843C>T;Mutation_AA_syntax=p.L615L;Tumour_Site_(cosmic)=large_intestine,thyroid;Frequency_(cosmic)=8.82,33.33;HGVS_Syntax(COSMIC)=c.1843C>Tp.L615L;OMIM_ID=OMIM:610770;Gene_Description=894679;pValue=1.0E-255;Zygosity=HET;Category=Category//@III-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/0:0,255,255:10
chr1	883625	.	A	G	123.0	PASS	ALTCOUNT=38;DP=38.0;DP4=1,0,20,18;AF1=1.0;MQ=41;IsKnownVariant=0;dbnsfpUniprot_acc;dbnsfpInterpro_domain;dbnsfpEnsembl_transcriptid;dbnsfpSIFT_score;dbnsfpGERP++_NR;dbnsfpGERP++_RS;dbnsfp29way_logOdds;dbnsfp1000Gp1_AF;dbnsfp1000Gp1_AFR_AF;dbnsfp1000Gp1_EUR_AF;dbnsfp1000Gp1_AMR_AF;dbnsfp1000Gp1_ASN_AF;dbnsfpESP5400_AA_AF;EFF=DOWNSTREAM(MODIFIER||||SAMD11|mRNA|CODING|NM_152486|),INTRON(MODIFIER||||NOC2L|mRNA|CODING|NM_015658|);SEL_PRIMARY_EFF=1;OMIM_ID=OMIM:610770;Gene_Description=894679;pValue=1.0E-123;Zygosity=HOM;Category=Category//@III-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/1:0,0,255:255
chr1	884091	.	C	G	255.0	PASS	ALTCOUNT=14;DP=35.0;DP4=2,20,1,13;AF1=0.4;MQ=41;IsKnownVariant=0;dbnsfpUniprot_acc;dbnsfpInterpro_domain;dbnsfpEnsembl_transcriptid;dbnsfpSIFT_score;dbnsfpGERP++_NR;dbnsfpGERP++_RS;dbnsfp29way_logOdds;dbnsfp1000Gp1_AF;dbnsfp1000Gp1_AFR_AF;dbnsfp1000Gp1_EUR_AF;dbnsfp1000Gp1_AMR_AF;dbnsfp1000Gp1_ASN_AF;dbnsfpESP5400_AA_AF;EFF=DOWNSTREAM(MODIFIER||||SAMD11|mRNA|CODING|NM_152486|),INTRON(MODIFIER||||NOC2L|mRNA|CODING|NM_015658|);SEL_PRIMARY_EFF=1;OMIM_ID=OMIM:610770;Gene_Description=894679;pValue=1.0E-255;Zygosity=HET;Category=Category//@III-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/0:0,255,255:10
chr1	884101	.	A	C	255.0	PASS	ALTCOUNT=12;DP=29.0;DP4=2,16,2,10;AF1=0.41379312;MQ=41;IsKnownVariant=0;dbnsfpUniprot_acc;dbnsfpInterpro_domain;dbnsfpEnsembl_transcriptid;dbnsfpSIFT_score;dbnsfpGERP++_NR;dbnsfpGERP++_RS;dbnsfp29way_logOdds;dbnsfp1000Gp1_AF;dbnsfp1000Gp1_AFR_AF;dbnsfp1000Gp1_EUR_AF;dbnsfp1000Gp1_AMR_AF;dbnsfp1000Gp1_ASN_AF;dbnsfpESP5400_AA_AF;EFF=DOWNSTREAM(MODIFIER||||SAMD11|mRNA|CODING|NM_152486|),INTRON(MODIFIER||||NOC2L|mRNA|CODING|NM_015658|);SEL_PRIMARY_EFF=1;OMIM_ID=OMIM:610770;Gene_Description=894679;pValue=1.0E-255;Zygosity=HET;Category=Category//@III-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/0:0,255,255:10
chr1	886788	.	G	A	123.0	PASS	ALTCOUNT=26;DP=26.0;DP4=1,0,2,24;AF1=1.0;MQ=41;IsKnownVariant=0;dbnsfpUniprot_acc;dbnsfpInterpro_domain;dbnsfpEnsembl_transcriptid;dbnsfpSIFT_score;dbnsfpGERP++_NR;dbnsfpGERP++_RS;dbnsfp29way_logOdds;dbnsfp1000Gp1_AF;dbnsfp1000Gp1_AFR_AF;dbnsfp1000Gp1_EUR_AF;dbnsfp1000Gp1_AMR_AF;dbnsfp1000Gp1_ASN_AF;dbnsfpESP5400_AA_AF;EFF=INTRON(MODIFIER||||NOC2L|mRNA|CODING|NM_015658|);SEL_PRIMARY_EFF=0;OMIM_ID=OMIM:610770;Gene_Description=894679;pValue=1.0E-123;Zygosity=HOM;Category=Category//@III-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/1:0,0,255:255
chr1	886817	.	C	T	123.0	PASS	ALTCOUNT=15;DP=15.0;DP4=1,0,1,14;AF1=1.0;MQ=41;IsKnownVariant=0;dbnsfpUniprot_acc;dbnsfpInterpro_domain;dbnsfpEnsembl_transcriptid;dbnsfpSIFT_score;dbnsfpGERP++_NR;dbnsfpGERP++_RS;dbnsfp29way_logOdds;dbnsfp1000Gp1_AF;dbnsfp1000Gp1_AFR_AF;dbnsfp1000Gp1_EUR_AF;dbnsfp1000Gp1_AMR_AF;dbnsfp1000Gp1_ASN_AF;dbnsfpESP5400_AA_AF;EFF=INTRON(MODIFIER||||NOC2L|mRNA|CODING|NM_015658|);SEL_PRIMARY_EFF=0;OMIM_ID=OMIM:610770;Gene_Description=894679;pValue=1.0E-123;Zygosity=HOM;Category=Category//@III-Default//@Categorization;state=ALGORITHM_GENERATED	GT:PL:GQ	1/1:0,0,255:255
```

**Comment by martijnvermaat** [comment]
The header of your VCF file defines the `PL` format field to consist of one integer value, while the records have a list of three integer values. This seems to be an issue in the software used to create the VCF file.

**Comment by stanedav** [comment]
Hello thank you for answer, I will try different software to create VCF. Thank you very much

**Comment by kowsalya1997** [comment]
Hi,
   I am getting  error like this,can anyone help me to fix this error?
(open_cv) F:\proj\emotion\Emotion-Recognition-master>python data_org.py
Traceback (most recent call last):
  File "data_org.py", line 14, in <module>
    emotion = int(float(file.readline())) #emotions are encoded as a float, readline as float, then convert to integer.
ValueError: invalid literal for float(): 9.0000000e+00   4.0000000e+00
