### ISSUE TITLE
Mismatch between FORMAT and sample columns cause IndexError

### ISSUE THREAD

**Issue by joaoe** [jamescasbon/PyVCF#298]
If the number of values in the FORMAT column is different from the number of values in the sample columns, the parser crashes.

Testcase
```
import io
import vcf

# The bug
vcf_blob = """#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tsample1
chr1\t123123123\tidX\tA\tC\t1\tPASS\tIN=FO\tA\t1:2
"""
list(vcf.Reader(io.StringIO(vcf_blob)))

# A more extensive testcase
vcf_blob = """#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tsample1
chr1\t123123123\tidX\tA\tC\t1\tPASS\tIN=FO\t.\t1:2
chr1\t123123123\tidX\tA\tC\t1\tPASS\tIN=FO\tA\t1:2
chr1\t123123123\tidX\tA\tC\t1\tPASS\tIN=FO\tA:B\t1:2
chr1\t123123123\tidX\tA\tC\t1\tPASS\tIN=FO\tA:B:C\t1:2
"""
list(vcf.Reader(io.StringIO(vcf_blob)))
```

Crash:
```
Traceback (most recent call last):
  File "a.py", line 7, in <module>
    list(vcf.Reader(io.StringIO(vcf_blob)))
  File "<env>/lib/python3.6/site-packages/vcf/parser.py", line 586, in __next__
    samples = self._parse_samples(row[9:], fmt, record)
  File "<env>/lib/python3.6/site-packages/vcf/parser.py", line 466, in _parse_samples
    if samp_fmt._fields[i] == 'GT':
IndexError: tuple index out of range
```

**Comment by joaoe** [comment]
Suggested fix
```
--- a/vcf/parser.py	2018-08-13 18:15:35.494032216 +0200
+++ b/vcf/parser.py	2018-08-13 18:15:39.869965849 +0200
@@ -461,6 +461,8 @@
             sampdat = [None] * nfields
 
             for i, vals in enumerate(sample.split(':')):
+                if i >= nfields:
+                    break
 
                 # short circuit the most common
                 if samp_fmt._fields[i] == 'GT':
```

**Comment by joaoe** [comment]
A bonus caught when making the testcase
```
Traceback (most recent call last):
  ...
  File "<project>/PyVCF/build/lib/vcf/parser.py", line 433, in _parse_sample_format
    samp_fmt = make_calldata_tuple(samp_fmt.split(':'))
  File "<project>/PyVCF/build/lib/vcf/model.py", line 685, in make_calldata_tuple
    class CallData(collections.namedtuple('calldata', fields)):
  File "<env>/lib/python3.6/collections/__init__.py", line 401, in namedtuple
    'identifiers: %r' % name)
ValueError: Type names and field names must be valid identifiers: ''
```
The names of the columns in the FORMAT column are used verbatim to create properties in a `namedtuple` which will crash when the column names are not valid python identifiers. The committed fix renames the columns although a better solution would be to replace the `namedtuple` with a `collections.OreredDict`.
