### ISSUE TITLE
Custom section delimited by ";" and not ":"

### ISSUE THREAD

**Issue by BioComSoftware** [jamescasbon/PyVCF#325]
While attempting to parse a VCF file, a custom segment "DBSNP" (using a similar format to "INFO") is delimited by semi-colons (";") and not the expected colon (":"). As such an error arises...

`Traceback (most recent call last):`
`  File "/<redacted>/VCFcrawl.py", line 15, in <module>
    for i in o.dump():`
`  File "/<redacted>/VCFcrawl.py", line 9, in dump
    for record in vcf_reader:`
`  File "/<virtualenv>/lib/python3.6/site-packages/vcf/parser.py", line 590, in __next__
    samples = self._parse_samples(row[9:], fmt, record)`
`  File "/<virtualenv>/lib/python3.6/site-packages/vcf/parser.py", line 489, in _parse_samples
    sampdat[i] = float(vals)`
`ValueError: could not convert string to float: '<int>;WGT<int>;VC<alpha>;SLO;INT;ASP;G5A;G5;GNO;KGPhase1;ID=<alphanum>&MATCH=exact;POS=<int>;END=<int>;RS<int>;RSPOS<int>;dbSNPBuildID<int>;SSR<int>;SAO<int>;VP=<hex>;GENEINFO=<alphanum>'`
*Actual values redacted from `vals` for privacy

The error arises from ...
- the parser.py `def _parse_samples(self, samples, samp_fmt, site):` (line 436)
- lines (starting at 497) `elif entry_type == 'Float': sampdat[i] = float(vals)` 
... where `vals` still contains the entire string `vals = '<int>;WGT<int>;VC<alpha>;SLO;INT;ASP;G5A;G5;GNO;KGPhase1;ID=<alphanum>&MATCH=exact;POS=<int>;END=<int>;RS<int>;RSPOS<int>;dbSNPBuildID<int>;SSR<int>;SAO<int>;VP=<hex>;GENEINFO=<alphanum>'`
*Actual values redacted from `vals` for privacy

**Comment by BioComSoftware** [comment]
Error modifies after fork'ing the project to my own Github for troubleshooting.

`../site-packages/PyVCF-0.6.8-py3.6.egg/vcf/`

`Traceback (most recent call last):`
`  File "/<redacted>/VCFcrawl.py", line 15, in <module>
    for i in o.dump():`
`  File "/<redacted>/VCFcrawl.py", line 9, in dump
    for record in vcf_reader:`
`  File "/<virtualenv>/lib/python3.6/site-packages/PyVCF-0.6.8-py3.6.egg/vcf/parser.py", line 591, in __next__
    samples = self._parse_samples(row[9:], fmt, record)`
`  File "/<virtualenv>/lib/python3.6/site-packages/PyVCF-0.6.8-py3.6.egg/vcf/parser.py", line 513, in _parse_samples
    sampdat[i] = _map(float, vals)`
`  File "/<virtualenv>/lib/python3.6/site-packages/PyVCF-0.6.8-py3.6.egg/vcf/parser.py", line 360, in _map
    for x in iterable]`
`  File "/<virtualenv>/lib/python3.6/site-packages/PyVCF-0.6.8-py3.6.egg/vcf/parser.py", line 360, in <listcomp>
    for x in iterable]`
`ValueError: could not convert string to float: `
`'<int>;WGT<int>;VC<alpha>;SLO;INT;ASP;G5A;G5;GNO;KGPhase1;ID=<alphanum>&MATCH=exact;POS=<int>;END=<int>;RS<int>;RSPOS<int>;dbSNPBuildID<int>;SSR<int>;SAO<int>;VP=<hex>;GENEINFO=<alphanum>'`
*Actual values redacted from vals for privacy

**Comment by BioComSoftware** [comment]
As it turns out, the issue was not the delimiter, it was that the VCF file had additional, non-standard headers and columns that came after the Genotype fields. These columns contained info similarly formatted like the INFO column. It contained data with colons (such as `GENEINFO=PRDM2:7799`) which the Genotype parser attempted to add into the Genotype "samples" list. Since it didn't match the expected format of "GT:GL:GOF:GQ:NR:NV" the code crashed (it split the line on at the GENEINFO=PRDM2[\n]7799` creating a garbage row it couldn't parse.) 

I modified the PyVCF code to accept VCF files with additional non-standard headers/columns. In `parser.py`, `__next__()` method you used a list "row" which is accessed by hardcoded indexes (`row[0] - row[9]`). I replaced this with a dictionary which is derived by parsing the headers row (identified by starting with `#CHROM`). It then uses the headers as dict keys, and (for each data row) creates a "rowdict" variable containing "header1":"column_1_data", "header2":"column_2_data". This way, additional nonstandard columns don't crash the software. 

I did _not_ go so far as to modify the `_parse_samples()` method, so (right now, in this code) the additional columns are still being added to the Genotype samples. 

I passed this code up as a pull request so you could decide if there's any value for it in the master PyVCF. 

Thanks!
Mike
