### ISSUE TITLE
Write --output

### ISSUE THREAD

**Issue by tahirasma** [jamescasbon/PyVCF#333]
Greetings!

When the command was run, it gave the following error:

```
Traceback (most recent call last):
  File "./vcf_filter.py", line 168, in <module>
    if __name__ == '__main__': main()
  File "./vcf_filter.py", line 142, in main
    output = vcf.Writer(args.output, inp)
  File "/usr/lib/python2.7/site-packages/vcf/parser.py", line 644, in __init__
    quotechar='', quoting=csv.QUOTE_NONE)
TypeError: argument 1 must have a "write" method
```
The command is: 
`python2.7 ./vcf_filter.py --output test.vcf.out test.vcf dps --depth-per-sample 6`

Looking forward to your assistance.

**Comment by tahirasma** [comment]
It is solved by modifying code from:

`output = vcf.Writer(args.output, inp)`

to 

`output = vcf.Writer(open(args.output,'w'), inp)`
