### ISSUE TITLE
Cannot use import vfc

### ISSUE THREAD

**Issue by doctorasgr** [jamescasbon/PyVCF#336]
Hi everyone,
I just installed PyVCF today and after tried to run `import vcf` what I see in my terminal is this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\my_user_folder\anaconda3\envs\my_sprint\lib\site-packages\vcf\__init__.py", line 166, in <module>
    from parser import Reader, Writer
ImportError: cannot import name 'Reader' from 'parser' (unknown location)
```

Any ideas why?

I went to the **__init__.py** and opened this in the editor and all I can see is:
```
from parser import Reader, Writer <====== this is the line 166
from parser import VCFReader, VCFWriter
from filters import Base as Filter
from parser import RESERVED_INFO, RESERVED_FORMAT

VERSION = '0.4.3'
```

**Comment by dridk** [comment]
Hi, PyVCF is not maintained anymore. We do not have any feedback from the author since a while. 
I suggest to use PyVCF3 instead : 
https://github.com/dridk/PyVCF3
