### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by josetb** [jamescasbon/PyVCF#69]
Hi,

when I try to install PyVCF 0.6.0 through python setup.py install on a mac I get the following:

error: can't copy 'vcf/cparse.c': doesn't exist or not a regular file

The file ins't in the vcf directory. Am I doing something wrong? Did I miss a step?

thanks

jm

**Comment by tinuthomas** [comment]
Trying to install PyVCF, getting the following error

running build_ext
Traceback (most recent call last):
  File "setup.py", line 85, in <module>
    **extras
  File "/usr/local/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 73, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 88, in do_egg_install
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/bdist_egg.py", line 185, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/bdist_egg.py", line 171, in call_command
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install_lib.py", line 8, in run
  File "/usr/local/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.6/site-packages/Cython/Distutils/build_ext.py", line 135, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib64/python2.6/site-packages/Cython/Distutils/build_ext.py", line 142, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/usr/lib64/python2.6/site-packages/Cython/Distutils/build_ext.py", line 153, in cython_sources
    from Cython.Compiler.Main \
  File "/usr/lib64/python2.6/site-packages/Cython/Compiler/Main.py", line 19, in <module>
    import Code
  File "Code.py", line 298, in init Cython.Compiler.Code (Cython/Compiler/Code.c:32516)
  File "/usr/local/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: unexpected end of regular expression

**Comment by similarface** [comment]
error: can't copy 'vcf/cparse.c': doesn't exist or not a regular file
solution：
[root@localhost vcf]# ls
cparse.pyx  filters.py  __init__.py  model.py  parser.py  sample_filter.py  test  utils.py
[root@localhost vcf]# cython cparse.pyx 
[root@localhost vcf]# ls
cparse.c  cparse.pyx  filters.py  __init__.py  model.py  parser.py  sample_filter.py  test  utils.py
[root@localhost PyVCF-0.6.8]# python2.7 setup.py install
...
Finished processing dependencies for PyVCF==0.6.8

**Comment by aflyhorse** [comment]
Same problem here. Missing cparse.c. Manual generation works.
I am using pip 8.1.2 with setuptools 23.0.0
